services:
  - type: web
    name: bengkelbenteng-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <GANTI-DI-RENDER>
      - key: APP_URL
        value: https://<NAMA-APP>.onrender.com
      - key: VITE_APP_URL
        value: https://<NAMA-APP>.onrender.com
